/** Career paths, licences, professional development and knowledge transfer (Phase 09). */
export const careerAr = {
  career: {
    nav: 'المسارات والرخص', pdNav: 'التطوير المهني', myNav: 'نموّي المهني',
    tabs: { paths: 'المسارات', compliance: 'الامتثال', licences: 'سجل الرخص', activities: 'أنشطة التطوير', recognitions: 'طلبات الاعتراف', types: 'الأنواع والقواعد', targets: 'الحد الأدنى السنوي', report: 'التقارير', transfers: 'نقل المعرفة' },
    types: { promotion: 'ترقية', licence: 'رخصة مهنية', specialisation: 'تخصص' },
    path: { new: 'مسار جديد', titleAr: 'العنوان بالعربية', titleEn: 'العنوان بالإنجليزية', type: 'النوع', levels: 'المستويات', addLevel: 'إضافة مستوى', level: 'المستوى {{n}}', conditions: 'الشروط', addCondition: 'إضافة شرط', field: 'الحقل', operator: 'العملية', value: 'القيمة', programs: 'البرامج المطلوبة', addGroup: 'مجموعة برامج', anyOf: 'أي كم منها', pdHours: 'ساعات تطوير مهني كحد أدنى', validity: 'مدة الصلاحية (شهر)', evaluate: 'تقييم الجميع الآن', evaluated: 'تم تقييم {{n}} موظفاً', saved: 'حُفظ المسار', achieve: 'منح المستوى', achieved: 'مُنح المستوى', funnel: 'القمع حسب المستوى', matrix: 'المصفوفة', employees: 'الموظفون', eligibleFor: 'مؤهلون للمستوى', export: 'تصدير', missing: 'ينقصه', empty: 'لا مسارات.' },
    status: { not_started: 'لم يبدأ', in_progress: 'قيد التقدم', eligible: 'مؤهل', achieved: 'محقق', expired: 'منتهٍ', lost: 'مفقود' },
    ops: { gte: '≥', gt: '>', lte: '≤', lt: '<', eq: '=', neq: '≠', in: 'ضمن', completed: 'أنجز' },
    licence: { title: 'الرخص المهنية', number: 'رقم الرخصة', level: 'المستوى', issued: 'الإصدار', expires: 'الانتهاء', status: { active: 'سارية', expired: 'منتهية', suspended: 'موقوفة' }, add: 'إضافة رخصة', import: 'استيراد CSV', imported: 'أُنشئ {{created}} وحُدّث {{updated}} وفشل {{errors}}', importHint: 'الأعمدة: employee_no, level_no, licence_no, issued_at, expires_at', source: 'المصدر', expiring: 'تنتهي خلال ٩٠ يوماً', empty: 'لا رخص.' },
    pd: { title: 'التطوير المهني', log: 'تسجيل نشاط', type: 'النوع', activityTitle: 'عنوان النشاط', provider: 'الجهة المقدّمة', domain: 'المجال', start: 'تاريخ البدء', hours: 'الساعات المعلنة', level: 'مستوى المشاركة', levels: { attendee: 'حضور', presenter: 'مقدّم', organiser: 'منظّم', author: 'مؤلف' }, location: 'المكان', evidence: 'دليل المشاركة', recognition: 'اطلب اعتراف المركز بهذا النشاط', preview: 'ساعات محسوبة: {{n}}', save: 'حفظ مسودة', submit: 'إرسال للاعتماد', submitted: 'أُرسل للاعتماد', saved: 'حُفظ النشاط', status: { draft: 'مسودة', pending_manager: 'بانتظار المدير', approved: 'معتمد', rejected: 'مرفوض', returned: 'معاد للتعديل' }, approvedHours: 'المعتمد: {{n}} س', note: 'ملاحظة المدير', empty: 'لا أنشطة.', year: 'ساعات هذا العام', of: 'من {{n}}', shortfall: 'المتبقي {{n}}', sources: { center: 'برامج المركز', internal: 'ورش المدرسة', external: 'خارجي', knowledge_transfer: 'نقل المعرفة' }, team: 'أنشطة فريقك بانتظارك', approve: 'اعتماد', returnIt: 'إعادة', reject: 'رفض', decided: 'تم القرار' },
    centre: { hoursApproved: 'الساعات المعتمدة', recognise: 'اعتراف', recognisedHours: 'ساعات معترف بها', equivalents: 'برامج مكافئة', decide: 'قرار', pendingOnly: 'المعلّقة فقط', typeCode: 'الرمز', factor: 'المعامل', capActivity: 'سقف النشاط', capYear: 'سقف سنوي للنوع', evidenceRequired: 'الدليل إلزامي', active: 'مفعّل', addType: 'نوع جديد', year: 'السنة', minHours: 'الحد الأدنى للساعات', yearStart: 'شهر بداية السنة (١ = تقويمية)', counts: 'ما يُحتسب', capSource: 'سقف المصدر', addTarget: 'حد جديد', below: 'دون الحد: {{n}}', byDomain: 'حسب المجال', approval: 'نسب الاعتماد' },
    kt: { title: 'نقل المعرفة', due: 'الموعد', status: { pending: 'مطلوب', pending_review: 'قيد المراجعة', approved: 'معتمد', rejected: 'غير معتمد' }, delivered: 'تاريخ التنفيذ', hours: 'الساعات', method: 'الطريقة', methods: { workshop: 'ورشة', meeting: 'اجتماع', coaching: 'تدريب فردي', online: 'عن بُعد' }, beneficiaries: 'المستفيدون', search: 'ابحث عن زميل…', addName: 'إضافة اسم', evidence: 'دليل التنفيذ (كشف حضور/صور/عرض)', send: 'إرسال للمراجعة', sent: 'أُرسل للمراجعة', empty: 'لا مهام نقل معرفة.', setting: 'إعداد نقل المعرفة', required: 'مطلوب في هذا البرنامج', minBeneficiaries: 'أقل عدد مستفيدين', minHours: 'أقل ساعات', deadline: 'المهلة بعد الإتمام (يوم)', reach: 'المتدربون المباشرون {{d}} · المستفيدون غير المباشرين {{i}} · ساعات {{h}}', approve: 'اعتماد', reject: 'رفض', note: 'ملاحظة' },
    my: { paths: 'مساراتي', next: 'الخطوة التالية', licences: 'رخصي', noPaths: 'لا مسارات تنطبق عليك.', conditionMet: 'مستوفى', conditionOpen: 'غير مستوفى', current: 'الحالي', target: 'المستهدف' },
  },
}

export const careerEn: typeof careerAr = {
  career: {
    nav: 'Paths and licences', pdNav: 'Professional development', myNav: 'My growth',
    tabs: { paths: 'Paths', compliance: 'Compliance', licences: 'Licence register', activities: 'PD activities', recognitions: 'Recognition requests', types: 'Types and rules', targets: 'Annual minimum', report: 'Reports', transfers: 'Knowledge transfer' },
    types: { promotion: 'Promotion', licence: 'Professional licence', specialisation: 'Specialisation' },
    path: { new: 'New path', titleAr: 'Title (Arabic)', titleEn: 'Title (English)', type: 'Type', levels: 'Levels', addLevel: 'Add a level', level: 'Level {{n}}', conditions: 'Conditions', addCondition: 'Add a condition', field: 'Field', operator: 'Operator', value: 'Value', programs: 'Required programs', addGroup: 'Program group', anyOf: 'Any … of them', pdHours: 'Minimum PD hours', validity: 'Validity (months)', evaluate: 'Evaluate everyone now', evaluated: '{{n}} employees evaluated', saved: 'Path saved', achieve: 'Grant the level', achieved: 'Level granted', funnel: 'Funnel by level', matrix: 'Matrix', employees: 'Employees', eligibleFor: 'Eligible for the level', export: 'Export', missing: 'Missing', empty: 'No paths.' },
    status: { not_started: 'Not started', in_progress: 'In progress', eligible: 'Eligible', achieved: 'Achieved', expired: 'Expired', lost: 'Lost' },
    ops: { gte: '≥', gt: '>', lte: '≤', lt: '<', eq: '=', neq: '≠', in: 'in', completed: 'completed' },
    licence: { title: 'Professional licences', number: 'Licence no.', level: 'Level', issued: 'Issued', expires: 'Expires', status: { active: 'Active', expired: 'Expired', suspended: 'Suspended' }, add: 'Add a licence', import: 'Import CSV', imported: 'Created {{created}}, updated {{updated}}, failed {{errors}}', importHint: 'Columns: employee_no, level_no, licence_no, issued_at, expires_at', source: 'Source', expiring: 'Expiring within 90 days', empty: 'No licences.' },
    pd: { title: 'Professional development', log: 'Log an activity', type: 'Type', activityTitle: 'Activity title', provider: 'Provider', domain: 'Domain', start: 'Start date', hours: 'Declared hours', level: 'Participation level', levels: { attendee: 'Attendee', presenter: 'Presenter', organiser: 'Organiser', author: 'Author' }, location: 'Location', evidence: 'Evidence of participation', recognition: 'Ask the centre to recognise this activity', preview: 'Computed hours: {{n}}', save: 'Save draft', submit: 'Send for approval', submitted: 'Sent for approval', saved: 'Activity saved', status: { draft: 'Draft', pending_manager: 'Waiting for the manager', approved: 'Approved', rejected: 'Rejected', returned: 'Returned' }, approvedHours: 'Approved: {{n}} h', note: 'Manager note', empty: 'No activities.', year: 'Hours this year', of: 'of {{n}}', shortfall: '{{n}} to go', sources: { center: 'Centre programs', internal: 'School workshops', external: 'External', knowledge_transfer: 'Knowledge transfer' }, team: 'Your team’s activities waiting for you', approve: 'Approve', returnIt: 'Return', reject: 'Reject', decided: 'Decision recorded' },
    centre: { hoursApproved: 'Approved hours', recognise: 'Recognition', recognisedHours: 'Recognised hours', equivalents: 'Equivalent programs', decide: 'Decide', pendingOnly: 'Pending only', typeCode: 'Code', factor: 'Factor', capActivity: 'Cap per activity', capYear: 'Yearly cap for the type', evidenceRequired: 'Evidence required', active: 'Active', addType: 'New type', year: 'Year', minHours: 'Minimum hours', yearStart: 'Year start month (1 = calendar)', counts: 'What counts', capSource: 'Source cap', addTarget: 'New target', below: 'Below target: {{n}}', byDomain: 'By domain', approval: 'Approval rates' },
    kt: { title: 'Knowledge transfer', due: 'Due', status: { pending: 'Required', pending_review: 'In review', approved: 'Approved', rejected: 'Not approved' }, delivered: 'Delivered on', hours: 'Hours', method: 'Method', methods: { workshop: 'Workshop', meeting: 'Meeting', coaching: 'Coaching', online: 'Online' }, beneficiaries: 'Beneficiaries', search: 'Find a colleague…', addName: 'Add a name', evidence: 'Evidence (attendance sheet / photos / slides)', send: 'Send for review', sent: 'Sent for review', empty: 'No knowledge-transfer tasks.', setting: 'Knowledge-transfer setting', required: 'Required in this program', minBeneficiaries: 'Minimum beneficiaries', minHours: 'Minimum hours', deadline: 'Deadline after completion (days)', reach: 'Direct trainees {{d}} · indirect beneficiaries {{i}} · hours {{h}}', approve: 'Approve', reject: 'Reject', note: 'Note' },
    my: { paths: 'My paths', next: 'Next step', licences: 'My licences', noPaths: 'No path applies to you.', conditionMet: 'Met', conditionOpen: 'Not met', current: 'Current', target: 'Target' },
  },
}
