/** Content packages, standards, LTI, library, sharing, providers and offline (Phase 10). */
export const contentAr = {
  content: {
    noPackage: 'لا توجد حزمة محتوى مرتبطة بهذا الدرس.', navStandards: 'المعايير والتكاملات', navLibraryAdmin: 'إدارة المكتبة', navLibrary: 'المكتبة الرقمية', navSharing: 'المشاركة والمجموعات',
    lesson: { package: 'حزمة محتوى', lti: 'أداة LTI', external: 'مقرر خارجي', pickPackage: 'اختر الحزمة', upload: 'رفع حزمة (SCORM / xAPI / cmi5 / H5P / HTML5 / Common Cartridge)', uploading: 'جارٍ الرفع والفحص…', unit: 'الوحدة المراد تشغيلها', requirePass: 'يشترط النجاح لإكمال الدرس', tool: 'أداة LTI', selectFromTool: 'اختيار محتوى من الأداة', preview: 'معاينة', standards: { scorm12: 'SCORM 1.2', scorm2004: 'SCORM 2004', cmi5: 'cmi5', xapi: 'xAPI', h5p: 'H5P', html5: 'HTML5', cc: 'Common Cartridge' } },
    versions: { title: 'إصدارات الدرس', current: 'الحالي', publish: 'نشر إصدار جديد', note: 'ملاحظة الإصدار', learners: 'المتدربون الجارون في الدرس', keep: 'يبقون على إصدارهم', move: 'ينتقلون إلى الجديد', restore: 'استرجاع', archive: 'أرشفة', diff: 'مقارنة', archived: 'مؤرشف', published: 'نُشر الإصدار', noChanges: 'لا تغييرات.', changed: 'تغيّر: {{f}}' },
    cc: { title: 'استيراد Common Cartridge', pick: 'اختر ملف .imscc أو .zip', tree: 'ما سيُستورد', becomes: { folder: 'مجلد', lesson: 'درس مقال', material: 'مادة تدريبية', bank: 'بنك أسئلة', link: 'درس رابط', lti: 'أداة LTI (غير مفعّلة)', discussion: 'نقاش (يتفعّل مع المجتمعات)', unsupported: 'غير مدعوم' }, import: 'استيراد المحدد', done: 'استُورد: {{lessons}} دروس، {{materials}} مواد، {{questions}} أسئلة، {{links}} روابط، {{lti}} أدوات', skipped: 'تُخطّي: {{n}}' },
    qti: { import: 'استيراد QTI', export: 'تصدير QTI 2.1', result: 'QTI: أُضيف {{created}}، غير مدعوم {{u}}، أخطاء {{e}}' },
    standards: { title: 'المعايير والتكاملات', lrs: 'مخزن السجلات LRS (xAPI)', endpoint: 'عنوان LRS', creds: 'بيانات الدخول', label: 'الاسم', scope: 'الصلاحية', scopes: { read: 'قراءة', write: 'كتابة', readwrite: 'قراءة وكتابة' }, add: 'إنشاء بيانات دخول', secretOnce: 'السر (يظهر مرة واحدة): {{key}} / {{secret}}', forward: 'تمرير إلى LRS خارجي', enabled: 'مفعّل', url: 'العنوان', key: 'المفتاح', secret: 'السر', caliper: 'IMS Caliper', apiKey: 'مفتاح API', sensor: 'معرّف المستشعر', pending: 'بانتظار الإرسال: {{n}} — فاشل: {{f}}', flush: 'إرسال الآن', offline: 'التعلم دون اتصال', expiry: 'صلاحية التنزيل (يوم)', save: 'حفظ', saved: 'حُفظت الإعدادات', remove: 'حذف', tabs: { lrs: 'LRS و Caliper', lti: 'أدوات LTI', providers: 'مزوّدو المحتوى', libraries: 'المكتبات الخارجية' } },
    lti: { title: 'أدوات LTI', platform: 'بيانات المنصة (تُعطى للأداة)', issuer: 'المُصدِر', jwks: 'JWKS', auth: 'رابط المصادقة', tokenUrl: 'رابط الرمز', dlReturn: 'عودة Deep Linking', outcomes: 'Outcomes (1.1)', rotate: 'تدوير المفاتيح', new: 'أداة جديدة', name: 'الاسم', version: 'الإصدار', clientId: 'Client ID', deployment: 'Deployment ID', loginUrl: 'رابط تسجيل الدخول (OIDC)', launchUrl: 'رابط الإطلاق', jwksUrl: 'JWKS الأداة', publicKey: 'المفتاح العام (اختياري)', deepLinkUrl: 'رابط Deep Linking', consumerKey: 'Consumer key', consumerSecret: 'Consumer secret', shareName: 'مشاركة الاسم', shareEmail: 'مشاركة البريد', ags: 'يدعم AGS/NRPS', active: 'مفعّلة', saved: 'حُفظت الأداة' },
    providers: { title: 'مزوّدو المحتوى', sync: 'مزامنة الآن', synced: 'كتالوج {{courses}} · إكمالات {{completed}}', driver: 'النمط', base: 'عنوان API', catalogue: 'مسار الكتالوج', completions: 'مسار الإكمالات', catalogueTitle: 'الكتالوج', makeProgram: 'إنشاء برنامج', programMade: 'أُنشئ البرنامج', reviews: 'إكمالات بانتظار المراجعة', approve: 'اعتماد', reject: 'رفض', note: 'ملاحظة' },
    libs: { title: 'المكتبات الخارجية', search: 'بحث في المكتبات الخارجية…', import: 'إضافة للمكتبة', deepLink: 'فتح البحث في المكتبة', searchUrl: 'رابط البحث (استخدم {q})', apiUrl: 'رابط API (اختياري)', imported: 'أُضيف إلى المكتبة' },
    library: { title: 'المكتبة الرقمية', search: 'ابحث بالعنوان أو المؤلف أو الموضوع…', all: 'الكل', types: { book: 'كتاب', journal: 'مجلة علمية', periodical: 'دورية', audio: 'صوتي', video: 'مرئي', elearning: 'تعلم إلكتروني', kit: 'حقيبة', link: 'رابط' }, sort: { recent: 'الأحدث', popular: 'الأكثر قراءة', title: 'العنوان' }, read: 'قراءة', download: 'تنزيل', shelf: 'رفّي', onShelf: 'على رفّي', add: 'إضافة لرفّي', empty: 'لا نتائج.', rights: 'الحقوق', viewOnly: 'للقراءة فقط', noDownload: 'التنزيل غير متاح بحكم الحقوق', noPrint: 'الطباعة غير متاحة', rate: 'قيّم', review: 'تعليقك', send: 'إرسال', shared: 'شُورك معي', collections: 'رفوف مختارة', myShelf: 'رفّي', reviews: '{{n}} تقييم', open: 'فتح', external: 'مكتبة خارجية' },
    admin: { items: 'عناصر المكتبة', newItem: 'عنصر جديد', titleAr: 'العنوان بالعربية', titleEn: 'العنوان بالإنجليزية', authors: 'المؤلفون (فاصلة)', publisher: 'الناشر', isbn: 'ISBN / ISSN', year: 'السنة', language: 'اللغة', subjects: 'المواضيع (فاصلة)', url: 'رابط', status: { draft: 'مسودة', published: 'منشور', archived: 'مؤرشف' }, owner: 'مالك الحقوق', licence: 'الترخيص', allowDownload: 'السماح بالتنزيل', allowPrint: 'السماح بالطباعة', watermark: 'علامة مائية باسم القارئ', embargoFrom: 'يُتاح من', embargoUntil: 'يُتاح حتى', audience: 'الجمهور (قواعد الأهلية)', addRule: 'إضافة قاعدة', file: 'الملف', cover: 'الغلاف', collectionsTab: 'الرفوف', newCollection: 'رف جديد', featured: 'مميّز', saved: 'حُفظ' },
    sharing: { title: 'المشاركة', share: 'مشاركة', with: 'مشاركة مع', targets: { program: 'برنامج', group: 'مجموعة تدريبية', job_group: 'مجموعة وظيفية', role: 'دور', user: 'شخص' }, permission: 'الصلاحية', permissions: { view: 'عرض', download: 'تنزيل', reshare: 'إعادة مشاركة' }, expires: 'ينتهي', done: 'تمت المشاركة', policies: 'سياسات المشاركة', role: 'الدور', resources: 'ما يمكن مشاركته', allowReshare: 'إعادة المشاركة', allowDownload: 'التنزيل', jobGroups: 'المجموعات الوظيفية', newGroup: 'مجموعة جديدة', members: '{{n}} عضو', ruleTitles: 'مسميات وظيفية', ruleCategories: 'فئات وظيفية', ruleSubjects: 'مواد', sharedEmpty: 'لا شيء شُورك معك.' },
    ext: { open: 'الانتقال إلى المقرر', done: 'أتممت المقرر', evidence: 'دليل الإتمام', note: 'ملاحظات', send: 'إرسال للمراجعة', sent: 'أُرسل للمراجعة' },
  },
}

export const contentEn: typeof contentAr = {
  content: {
    noPackage: 'No content package is attached to this lesson.', navStandards: 'Standards and integrations', navLibraryAdmin: 'Library management', navLibrary: 'Digital library', navSharing: 'Sharing and job groups',
    lesson: { package: 'Content package', lti: 'LTI tool', external: 'External course', pickPackage: 'Choose the package', upload: 'Upload a package (SCORM / xAPI / cmi5 / H5P / HTML5 / Common Cartridge)', uploading: 'Uploading and checking…', unit: 'Unit to play', requirePass: 'Passing is required to complete the lesson', tool: 'LTI tool', selectFromTool: 'Select content from the tool', preview: 'Preview', standards: { scorm12: 'SCORM 1.2', scorm2004: 'SCORM 2004', cmi5: 'cmi5', xapi: 'xAPI', h5p: 'H5P', html5: 'HTML5', cc: 'Common Cartridge' } },
    versions: { title: 'Lesson versions', current: 'Current', publish: 'Publish a new version', note: 'Version note', learners: 'Learners already in the lesson', keep: 'Stay on their version', move: 'Move to the new one', restore: 'Restore', archive: 'Archive', diff: 'Compare', archived: 'Archived', published: 'Version published', noChanges: 'No changes.', changed: 'Changed: {{f}}' },
    cc: { title: 'Import a Common Cartridge', pick: 'Choose an .imscc or .zip file', tree: 'What will be imported', becomes: { folder: 'Folder', lesson: 'Article lesson', material: 'Training material', bank: 'Question bank', link: 'Link lesson', lti: 'LTI tool (inactive)', discussion: 'Discussion (activates with communities)', unsupported: 'Unsupported' }, import: 'Import the selection', done: 'Imported: {{lessons}} lessons, {{materials}} materials, {{questions}} questions, {{links}} links, {{lti}} tools', skipped: 'Skipped: {{n}}' },
    qti: { import: 'Import QTI', export: 'Export QTI 2.1', result: 'QTI: added {{created}}, unsupported {{u}}, errors {{e}}' },
    standards: { title: 'Standards and integrations', lrs: 'Learning record store (xAPI)', endpoint: 'LRS endpoint', creds: 'Credentials', label: 'Name', scope: 'Access', scopes: { read: 'Read', write: 'Write', readwrite: 'Read and write' }, add: 'Create credentials', secretOnce: 'Secret (shown once): {{key}} / {{secret}}', forward: 'Forward to an external LRS', enabled: 'Enabled', url: 'URL', key: 'Key', secret: 'Secret', caliper: 'IMS Caliper', apiKey: 'API key', sensor: 'Sensor id', pending: 'Waiting to send: {{n}} — failed: {{f}}', flush: 'Send now', offline: 'Offline learning', expiry: 'Download validity (days)', save: 'Save', saved: 'Settings saved', remove: 'Delete', tabs: { lrs: 'LRS and Caliper', lti: 'LTI tools', providers: 'Content providers', libraries: 'External libraries' } },
    lti: { title: 'LTI tools', platform: 'Platform details (give these to the tool)', issuer: 'Issuer', jwks: 'JWKS', auth: 'Authentication URL', tokenUrl: 'Token URL', dlReturn: 'Deep Linking return', outcomes: 'Outcomes (1.1)', rotate: 'Rotate keys', new: 'New tool', name: 'Name', version: 'Version', clientId: 'Client ID', deployment: 'Deployment ID', loginUrl: 'Login URL (OIDC)', launchUrl: 'Launch URL', jwksUrl: 'Tool JWKS', publicKey: 'Public key (optional)', deepLinkUrl: 'Deep Linking URL', consumerKey: 'Consumer key', consumerSecret: 'Consumer secret', shareName: 'Share the name', shareEmail: 'Share the e-mail', ags: 'Supports AGS/NRPS', active: 'Active', saved: 'Tool saved' },
    providers: { title: 'Content providers', sync: 'Sync now', synced: 'Catalogue {{courses}} · completions {{completed}}', driver: 'Mode', base: 'API address', catalogue: 'Catalogue path', completions: 'Completions path', catalogueTitle: 'Catalogue', makeProgram: 'Create a program', programMade: 'Program created', reviews: 'Completions waiting for review', approve: 'Approve', reject: 'Reject', note: 'Note' },
    libs: { title: 'External libraries', search: 'Search the external libraries…', import: 'Add to the library', deepLink: 'Open the search in the library', searchUrl: 'Search URL (use {q})', apiUrl: 'API URL (optional)', imported: 'Added to the library' },
    library: { title: 'Digital library', search: 'Search by title, author or subject…', all: 'All', types: { book: 'Book', journal: 'Journal', periodical: 'Periodical', audio: 'Audio', video: 'Video', elearning: 'e-Learning', kit: 'Kit', link: 'Link' }, sort: { recent: 'Newest', popular: 'Most read', title: 'Title' }, read: 'Read', download: 'Download', shelf: 'My shelf', onShelf: 'On my shelf', add: 'Add to my shelf', empty: 'No results.', rights: 'Rights', viewOnly: 'Read only', noDownload: 'Download is not available (rights)', noPrint: 'Printing is not available', rate: 'Rate', review: 'Your comment', send: 'Send', shared: 'Shared with me', collections: 'Featured shelves', myShelf: 'My shelf', reviews: '{{n}} ratings', open: 'Open', external: 'External library' },
    admin: { items: 'Library items', newItem: 'New item', titleAr: 'Title (Arabic)', titleEn: 'Title (English)', authors: 'Authors (comma)', publisher: 'Publisher', isbn: 'ISBN / ISSN', year: 'Year', language: 'Language', subjects: 'Subjects (comma)', url: 'Link', status: { draft: 'Draft', published: 'Published', archived: 'Archived' }, owner: 'Rights owner', licence: 'Licence', allowDownload: 'Allow download', allowPrint: 'Allow printing', watermark: 'Watermark with the reader’s name', embargoFrom: 'Available from', embargoUntil: 'Available until', audience: 'Audience (eligibility rules)', addRule: 'Add a rule', file: 'File', cover: 'Cover', collectionsTab: 'Shelves', newCollection: 'New shelf', featured: 'Featured', saved: 'Saved' },
    sharing: { title: 'Sharing', share: 'Share', with: 'Share with', targets: { program: 'Program', group: 'Training group', job_group: 'Job group', role: 'Role', user: 'Person' }, permission: 'Permission', permissions: { view: 'View', download: 'Download', reshare: 'Reshare' }, expires: 'Expires', done: 'Shared', policies: 'Sharing policies', role: 'Role', resources: 'What can be shared', allowReshare: 'Reshare', allowDownload: 'Download', jobGroups: 'Job groups', newGroup: 'New group', members: '{{n}} members', ruleTitles: 'Job titles', ruleCategories: 'Job categories', ruleSubjects: 'Subjects', sharedEmpty: 'Nothing was shared with you.' },
    ext: { open: 'Go to the course', done: 'I completed the course', evidence: 'Evidence of completion', note: 'Notes', send: 'Send for review', sent: 'Sent for review' },
  },
}
