/** The evaluation centre, form designer, settings and "My evaluations" (Phase 08). */
export const evalAr = {
  evalc: {
    tab: 'التقييم', nav: 'نماذج التقييم', settingsNav: 'إعدادات التقييم', group: 'المجموعة', all: 'كل المجموعات',
    sub: { board: 'لوحة الأدوات', results: 'النتائج', compare: 'قبلي / بعدي', interviews: 'المقابلات', report: 'تقرير التقييم' },
    kinds: { satisfaction: 'رضا المتدربين', impact_trainee: 'أثر التدريب — المتدرب', impact_manager: 'أثر التدريب — المدير المباشر', trainer_reflection: 'تأمل المدرب الذاتي', planning_evaluation: 'تقييم فريق التخطيط', supervisor_feedback: 'مشرف البرنامج', specialist_feedback: 'أخصائي التخطيط', custom: 'نموذج مخصص' },
    responses: '{{n}} من {{total}}', rate: 'نسبة الاستجابة', alertBanner: 'تنبيه رضا منخفض: المتوسط {{avg}}٪ ونسبة الاستجابة {{rate}}٪ (الحد {{threshold}}٪).', ruleNote: 'يُنبَّه القادة عندما تبلغ الاستجابة {{rate}}٪ فأكثر ويقل متوسط الرضا عن {{threshold}}٪.',
    assignments: 'التكليفات', respondent: 'المجيب', status: { pending: 'بانتظار الإجابة', submitted: 'تمت الإجابة', expired: 'انتهت المهلة' }, due: 'آخر موعد', remind: 'تذكير', reminded: 'أُرسل التذكير', assign: 'تكليف بنموذج', assigned: 'كُلّف {{n}}', form: 'النموذج', people: 'الأشخاص', noForms: 'لا نماذج معتمدة.',
    results: { hidden: 'ستظهر النتائج عند وصول {{n}} استجابات على الأقل حفاظاً على سرية المجيبين.', average: 'المتوسط', answered: 'أجاب', evidence: 'الأدلة المرفقة', openEvidence: 'فتح', noData: 'لا استجابات بعد.', score: 'الدرجة', comments: 'ملاحظات', export: 'تصدير' },
    cmp: { pre: 'القبلي', post: 'البعدي', gain: 'مكسب المعرفة', target: 'الهدف ≥ {{n}}٪', met: 'تحقق الهدف', notMet: 'لم يتحقق الهدف', pairs: 'متدربون لديهم الاختباران: {{n}}', distribution: 'توزيع المكاسب', buckets: { below_zero: 'أقل من صفر', zero_to_10: '٠–١٠٪', ten_to_25: '١٠–٢٥٪', twenty_five_to_50: '٢٥–٥٠٪', above_50: 'فوق ٥٠٪' }, skills: 'المكسب حسب المهارة', skill: 'المهارة', none: 'لا اختبارات قبلية وبعدية بعد.',
      sig: { insufficient: 'عدد الأزواج غير كافٍ لحكم إحصائي.', none: 'الفرق قد يكون بفعل الصدفة.', moderate: 'الفرق مؤكد على الأرجح (دلالة متوسطة).', strong: 'الفرق مؤكد بقوة.' }, effect: { negligible: 'أثر ضئيل', small: 'أثر صغير', medium: 'أثر متوسط', large: 'أثر كبير' } },
    interviews: { title: 'سجل المقابلات', add: 'مقابلة جديدة', held: 'تاريخ المقابلة', method: 'الطريقة', methods: { in_person: 'حضورية', online: 'عن بُعد', phone: 'هاتفية' }, sentiment: 'الانطباع', sentiments: { positive: 'إيجابي', neutral: 'محايد', negative: 'سلبي' }, who: 'المُقابَل', summary: 'الملخص', qa: 'أسئلة وإجابات', question: 'السؤال', answer: 'الإجابة', addQa: 'إضافة سؤال', links: 'روابط مرفقة (رابط في كل سطر)', empty: 'لا مقابلات.', saved: 'حُفظت المقابلة' },
    report: { title: 'تقرير تقييم البرنامج', generate: 'إعداد مسودة', metrics: 'مؤشرات', class: { successful_continue: 'ناجح — يُستمر فيه', needs_review: 'يحتاج مراجعة', weak_stop: 'ضعيف — يُوقف أو يُعاد تصميمه' }, reasons: 'أسباب التصنيف', state: { good: 'محقق', between: 'دون المرجو', low: 'ضعيف', missing: 'لا بيانات' }, strengths: 'نقاط القوة (سطر لكل نقطة)', improvements: 'فرص التحسين (سطر لكل نقطة)', recommendations: 'التوصيات', status: { draft: 'مسودة', reviewed: 'تمت المراجعة', approved: 'معتمد' }, markReviewed: 'إرسال للاعتماد', approve: 'اعتماد', approved: 'اعتُمد التقرير', saved: 'حُفظ التقرير', open: 'فتح', empty: 'لا تقارير بعد.', exportWord: 'Word', exportPdf: 'PDF', exportExcel: 'Excel', lang: 'لغة التقرير', metricNames: { attendance: 'الحضور', pass: 'النجاح', satisfaction: 'الرضا', gain: 'مكسب المعرفة', impact: 'الأثر' }, classification: 'التصنيف' },
    forms: { title: 'نماذج التقييم', new: 'نموذج جديد', kind: 'النوع', approval: { draft: 'مسودة', pending: 'بانتظار الاعتماد', approved: 'معتمد', returned: 'معاد' }, titleAr: 'العنوان بالعربية', titleEn: 'العنوان بالإنجليزية', evidence: 'يقبل دليلاً مرفقاً', evidenceAll: 'السماح بالأدلة في هذا النموذج', maxFiles: 'أقصى عدد مرفقات للسؤال', anonymous: 'مجهول الهوية', questionEn: 'نص السؤال بالإنجليزية', submit: 'إرسال للاعتماد', approve: 'اعتماد', returnIt: 'إعادة', saved: 'حُفظ النموذج', system: 'مرتبط بأداة قائمة (للعرض فقط)', version: 'الإصدار {{n}}', addQuestion: 'سؤال', note: 'ملاحظة', changedNote: 'تعديل نموذج معتمد ينشئ إصداراً جديداً يحتاج اعتماداً.' },
    settings: { title: 'إعدادات التقييم', impact: 'مواعيد نماذج الأثر', traineeDays: 'نموذج المتدرب بعد (يوم)', managerDays: 'نموذج المدير بعد (يوم)', optionalDays: 'نموذج إضافي بعد (يوم، اختياري)', reminderDays: 'تذكير بعد (يوم)', expiryDays: 'مهلة الإجابة (يوم)', alerts: 'تنبيه الرضا المنخفض', alertOn: 'تفعيل التنبيه', minRate: 'أقل نسبة استجابة %', threshold: 'حد الرضا %', recipients: 'من يُنبَّه', roles: { center_leadership: 'قيادات المركز', program_coordinator: 'مشرف البرنامج', planning_head: 'رئيس قسم التخطيط', center_admin: 'مدير المركز' }, classification: 'حدود تصنيف البرامج', satGood: 'رضا — المرجو', satLow: 'رضا — الحد الأدنى', gainGood: 'مكسب — المرجو', gainLow: 'مكسب — الحد الأدنى', impactGood: 'أثر — المرجو', impactLow: 'أثر — الحد الأدنى', anonymous: 'أقل عدد استجابات قبل إظهار النتائج المجهولة', saved: 'حُفظت الإعدادات' },
    my: { title: 'تقييماتي', empty: 'لا نماذج تقييم بانتظارك.', fill: 'تعبئة', done: 'تمت', evidence: 'دليل مرفق', addFile: 'إرفاق ملف', addLink: 'إضافة رابط', link: 'رابط (http…)', submit: 'إرسال', submitted: 'شكراً، وصلت إجابتك.', required: 'أجب عن الأسئلة المطلوبة', back: 'العودة', evidenceHint: 'PDF أو صورة أو ملف Office حتى ١٠ ميغابايت، أو رابط.' },
    impact: { evidence: 'أدلة التطبيق (ملفات أو روابط)' },
  },
}

export const evalEn: typeof evalAr = {
  evalc: {
    tab: 'Evaluation', nav: 'Evaluation forms', settingsNav: 'Evaluation settings', group: 'Group', all: 'All groups',
    sub: { board: 'Instrument board', results: 'Results', compare: 'Pre / post', interviews: 'Interviews', report: 'Evaluation report' },
    kinds: { satisfaction: 'Trainee satisfaction', impact_trainee: 'Training impact — trainee', impact_manager: 'Training impact — direct manager', trainer_reflection: 'Trainer self-reflection', planning_evaluation: 'Planning-team evaluation', supervisor_feedback: 'Program supervisor', specialist_feedback: 'Planning specialist', custom: 'Custom form' },
    responses: '{{n}} of {{total}}', rate: 'Response rate', alertBanner: 'Low satisfaction alert: average {{avg}}% with a {{rate}}% response rate (limit {{threshold}}%).', ruleNote: 'Leaders are alerted when the response rate reaches {{rate}}% and the average satisfaction is below {{threshold}}%.',
    assignments: 'Assignments', respondent: 'Respondent', status: { pending: 'Waiting', submitted: 'Answered', expired: 'Expired' }, due: 'Due', remind: 'Remind', reminded: 'Reminder sent', assign: 'Assign a form', assigned: '{{n}} assigned', form: 'Form', people: 'People', noForms: 'No approved forms.',
    results: { hidden: 'Results appear once at least {{n}} responses arrive, to protect respondents.', average: 'Average', answered: 'Answered', evidence: 'Attached evidence', openEvidence: 'Open', noData: 'No responses yet.', score: 'Score', comments: 'Comments', export: 'Export' },
    cmp: { pre: 'Pre', post: 'Post', gain: 'Knowledge gain', target: 'Target ≥ {{n}}%', met: 'Target met', notMet: 'Target not met', pairs: 'Trainees with both tests: {{n}}', distribution: 'Distribution of gains', buckets: { below_zero: 'Below zero', zero_to_10: '0–10%', ten_to_25: '10–25%', twenty_five_to_50: '25–50%', above_50: 'Above 50%' }, skills: 'Gain per skill', skill: 'Skill', none: 'No pre and post tests yet.',
      sig: { insufficient: 'Too few pairs for a statistical judgement.', none: 'The difference may be due to chance.', moderate: 'The difference is probably real (moderate evidence).', strong: 'The difference is very likely real.' }, effect: { negligible: 'Negligible effect', small: 'Small effect', medium: 'Medium effect', large: 'Large effect' } },
    interviews: { title: 'Interviews log', add: 'New interview', held: 'Held on', method: 'Method', methods: { in_person: 'In person', online: 'Online', phone: 'Phone' }, sentiment: 'Sentiment', sentiments: { positive: 'Positive', neutral: 'Neutral', negative: 'Negative' }, who: 'Interviewee', summary: 'Summary', qa: 'Questions and answers', question: 'Question', answer: 'Answer', addQa: 'Add a question', links: 'Attached links (one per line)', empty: 'No interviews.', saved: 'Interview saved' },
    report: { title: 'Program evaluation report', generate: 'Draft a report', metrics: 'Indicators', class: { successful_continue: 'Successful — continue', needs_review: 'Needs review', weak_stop: 'Weak — stop or redesign' }, reasons: 'Why this class', state: { good: 'Met', between: 'Below target', low: 'Low', missing: 'No data' }, strengths: 'Strengths (one per line)', improvements: 'Improvements (one per line)', recommendations: 'Recommendations', status: { draft: 'Draft', reviewed: 'Reviewed', approved: 'Approved' }, markReviewed: 'Send for approval', approve: 'Approve', approved: 'Report approved', saved: 'Report saved', open: 'Open', empty: 'No reports yet.', exportWord: 'Word', exportPdf: 'PDF', exportExcel: 'Excel', lang: 'Report language', metricNames: { attendance: 'Attendance', pass: 'Pass rate', satisfaction: 'Satisfaction', gain: 'Knowledge gain', impact: 'Impact' }, classification: 'Classification' },
    forms: { title: 'Evaluation forms', new: 'New form', kind: 'Kind', approval: { draft: 'Draft', pending: 'Awaiting approval', approved: 'Approved', returned: 'Returned' }, titleAr: 'Title (Arabic)', titleEn: 'Title (English)', evidence: 'Accepts attached evidence', evidenceAll: 'Allow evidence in this form', maxFiles: 'Maximum attachments per question', anonymous: 'Anonymous', questionEn: 'Question text (English)', submit: 'Send for approval', approve: 'Approve', returnIt: 'Return', saved: 'Form saved', system: 'Tied to an existing instrument (view only)', version: 'Version {{n}}', addQuestion: 'Question', note: 'Note', changedNote: 'Changing an approved form creates a new version that needs approval.' },
    settings: { title: 'Evaluation settings', impact: 'When the impact forms go out', traineeDays: 'Trainee form after (days)', managerDays: 'Manager form after (days)', optionalDays: 'Extra form after (days, optional)', reminderDays: 'Remind after (days)', expiryDays: 'Time to answer (days)', alerts: 'Low-satisfaction alert', alertOn: 'Alert on', minRate: 'Minimum response rate %', threshold: 'Satisfaction limit %', recipients: 'Who is alerted', roles: { center_leadership: 'Centre leadership', program_coordinator: 'Program supervisor', planning_head: 'Head of planning', center_admin: 'Centre admin' }, classification: 'Program classification limits', satGood: 'Satisfaction — target', satLow: 'Satisfaction — lower bound', gainGood: 'Gain — target', gainLow: 'Gain — lower bound', impactGood: 'Impact — target', impactLow: 'Impact — lower bound', anonymous: 'Minimum responses before anonymous results show', saved: 'Settings saved' },
    my: { title: 'My evaluations', empty: 'No evaluation forms are waiting for you.', fill: 'Fill in', done: 'Done', evidence: 'Evidence', addFile: 'Attach a file', addLink: 'Add a link', link: 'Link (http…)', submit: 'Submit', submitted: 'Thank you — your answers arrived.', required: 'Answer the required questions', back: 'Back', evidenceHint: 'PDF, image or Office file up to 10 MB, or a link.' },
    impact: { evidence: 'Evidence of application (files or links)' },
  },
}
