/** Passing policies, pass status, exceptions, two-stage task approval and certificate types (Phase 07). */
export const passAr = {
  passing: {
    tab: 'شروط النجاح', title: 'سياسة النجاح', global: 'السياسة العامة', globalHint: 'تنطبق على كل البرامج التي لا سياسة خاصة بها.', program: 'سياسة البرنامج', group: 'سياسة مجموعة', scope: 'النطاق', inherited: 'ترث السياسة من: {{from}}', none: 'لا سياسة محفوظة — تطبَّق القاعدة المعتادة (استيفاء كل المتطلبات).', remove: 'إزالة السياسة', removed: 'أُزيلت السياسة', saved: 'حُفظت سياسة النجاح',
    mode: 'طريقة الحساب', modes: { all_required: 'استيفاء كل المعايير', weighted: 'درجة مرجّحة' }, threshold: 'حد النجاح %', weights: 'مجموع الأوزان: {{sum}}٪', weightsOk: 'المجموع ١٠٠٪', required: 'إلزامي', minimum: 'الحد الأدنى %', weight: 'الوزن %',
    keys: { attendance: 'الحضور', participation: 'المشاركة', tasks: 'المهام', assessments: 'الاختبارات', course: 'المحتوى الإلكتروني', evaluation: 'تقييم البرنامج', knowledge_transfer: 'نقل المعرفة' },
    participationRules: 'ما الذي يُحتسب مشاركة', lessons: 'نشاط الدروس', sessionMarks: 'علامات المشاركة في الجلسات', hoursMode: 'الساعات في الشهادة', hours: { total: 'الساعات الكلية للبرنامج', actual: 'الساعات الفعلية للحضور' }, certTypes: 'أنواع الشهادات', types: { attendance: 'شهادة حضور', pass: 'شهادة نجاح', both: 'الاثنتان' }, attendanceMin: 'أقل حضور لشهادة الحضور %', surveyRequired: 'تعبئة الاستبيان شرط لتحميل الشهادة', taskApproval: 'اعتماد المهام', approvals: { trainer: 'المدرب', trainer_then_supervisor: 'المدرب ثم المشرف', auto: 'تلقائي للمهام ذاتية التقييم' },
    testOut: 'السماح بالنجاح باختبار شامل دون حضور', testOutAssessment: 'الاختبار الشامل', pick: 'اختر…', templates: 'قوالب الشهادات', templateAttendance: 'قالب شهادة الحضور', templatePass: 'قالب شهادة النجاح', defaultTemplate: 'القالب الافتراضي', assessmentWeights: 'الاختبارات المحتسبة وأوزانها (فارغ = كل اختبارات البرنامج)',
    simulate: 'محاكاة على المشاركين الحاليين', simulation: '{{n}} من {{total}} سينجحون', now: 'الحالي', wouldPass: 'سينجح', wouldFail: 'لن ينجح', save: 'حفظ السياسة',
    status: { pending: 'قيد التحقق', passed: 'ناجح', failed: 'لم ينجح', exempted: 'ناجح باستثناء' }, via: { standard: 'بالمعايير', test_out: 'باختبار المهارات', exception: 'باستثناء موثّق' },
    column: 'النجاح', details: 'تفاصيل النجاح', score: 'الدرجة المرجّحة', evidence: 'الدليل', met: 'مستوفى', notMet: 'غير مستوفى', na: 'غير مطلوب', exempt: 'مستثنى', hoursLine: 'الساعات: {{used}} (كلية {{total}} · فعلية {{actual}})',
    exceptions: 'الاستثناءات', grant: 'منح استثناء', criterion: 'المعيار', reason: 'السبب', attachment: 'المستند الداعم', granted: 'مُنح الاستثناء', revoke: 'إلغاء الاستثناء', revoked: 'أُلغي الاستثناء', revokedAt: 'أُلغي', by: 'بواسطة {{name}}',
    certAttendance: 'شهادة الحضور', certPass: 'شهادة النجاح', issue: 'إصدار', issued: 'صدرت',
    marks: 'مشاركة', participated: 'شارك',
    tasks: { trainer: 'قرار المدرب', supervisor: 'الاعتماد النهائي', pending_final: 'بانتظار المشرف', approve: 'اعتماد', returnIt: 'إعادة للتعديل', reject: 'رفض', finalApprove: 'اعتماد نهائي', selfAssessed: 'مهمة ذاتية التقييم (تُعتمد تلقائياً إن كانت السياسة تلقائية)', returned: 'أُعيدت {{n}} مرة' },
    my: { title: 'تقدّمي نحو النجاح', next: 'الخطوة التالية', attendNext: 'احضر {{n}}٪ إضافية', submitTask: 'سلّم المهام المتبقية ({{done}}/{{total}})', finishCourse: 'أكمل المحتوى الإلكتروني', fillSurvey: 'عبّئ تقييم البرنامج', testOut: 'اجتز الاختبار الشامل بدل الحضور', startTestOut: 'ابدأ الاختبار الشامل', allDone: 'استوفيت كل المعايير.', progress: 'التقدّم', open: 'تقدّمي' },
  },
}

export const passEn: typeof passAr = {
  passing: {
    tab: 'Passing rules', title: 'Passing policy', global: 'Global policy', globalHint: 'Applies to every program that has no policy of its own.', program: 'Program policy', group: 'Group policy', scope: 'Scope', inherited: 'Inherits the policy from: {{from}}', none: 'No saved policy — the usual rule applies (every requirement met).', remove: 'Remove the policy', removed: 'Policy removed', saved: 'Passing policy saved',
    mode: 'How it is calculated', modes: { all_required: 'Every criterion met', weighted: 'Weighted score' }, threshold: 'Pass mark %', weights: 'Weights total: {{sum}}%', weightsOk: 'Total 100%', required: 'Required', minimum: 'Minimum %', weight: 'Weight %',
    keys: { attendance: 'Attendance', participation: 'Participation', tasks: 'Tasks', assessments: 'Assessments', course: 'e-Course', evaluation: 'Program evaluation', knowledge_transfer: 'Knowledge transfer' },
    participationRules: 'What counts as participation', lessons: 'Lesson activity', sessionMarks: 'Participation marks in sessions', hoursMode: 'Hours on the certificate', hours: { total: 'Total program hours', actual: 'Hours actually attended' }, certTypes: 'Certificate types', types: { attendance: 'Attendance certificate', pass: 'Pass certificate', both: 'Both' }, attendanceMin: 'Minimum attendance for the attendance certificate %', surveyRequired: 'The survey is required to download the certificate', taskApproval: 'Task approval', approvals: { trainer: 'Trainer', trainer_then_supervisor: 'Trainer, then supervisor', auto: 'Automatic for self-assessed tasks' },
    testOut: 'Allow passing by a comprehensive test without attending', testOutAssessment: 'Comprehensive test', pick: 'Choose…', templates: 'Certificate templates', templateAttendance: 'Attendance certificate template', templatePass: 'Pass certificate template', defaultTemplate: 'Default template', assessmentWeights: 'Counted assessments and their weights (empty = all assessments of the program)',
    simulate: 'Simulate on current participants', simulation: '{{n}} of {{total}} would pass', now: 'Now', wouldPass: 'Would pass', wouldFail: 'Would not pass', save: 'Save the policy',
    status: { pending: 'Pending', passed: 'Passed', failed: 'Not passed', exempted: 'Passed by exception' }, via: { standard: 'By the criteria', test_out: 'By the skills test', exception: 'By a documented exception' },
    column: 'Passing', details: 'Passing details', score: 'Weighted score', evidence: 'Evidence', met: 'Met', notMet: 'Not met', na: 'Not required', exempt: 'Exempted', hoursLine: 'Hours: {{used}} (total {{total}} · attended {{actual}})',
    exceptions: 'Exceptions', grant: 'Grant an exception', criterion: 'Criterion', reason: 'Reason', attachment: 'Supporting document', granted: 'Exception granted', revoke: 'Revoke', revoked: 'Exception revoked', revokedAt: 'Revoked', by: 'by {{name}}',
    certAttendance: 'Attendance certificate', certPass: 'Pass certificate', issue: 'Issue', issued: 'Issued',
    marks: 'Participation', participated: 'Took part',
    tasks: { trainer: 'Trainer decision', supervisor: 'Final approval', pending_final: 'Waiting for the supervisor', approve: 'Approve', returnIt: 'Return for changes', reject: 'Reject', finalApprove: 'Final approval', selfAssessed: 'Self-assessed task (approved automatically when the policy is automatic)', returned: 'Returned {{n}} time(s)' },
    my: { title: 'My progress to pass', next: 'Next step', attendNext: 'Attend {{n}}% more', submitTask: 'Submit the remaining tasks ({{done}}/{{total}})', finishCourse: 'Finish the e-course', fillSurvey: 'Fill in the program evaluation', testOut: 'Pass the comprehensive test instead of attending', startTestOut: 'Start the comprehensive test', allDone: 'You met every criterion.', progress: 'Progress', open: 'My progress' },
  },
}
