<?php

namespace App\Deliverables;

use App\Services\Reports\DocxWriter;
use App\Services\ThemeService;
use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\MarkdownConverter;
use Mpdf\Mpdf;

/** Builds the generated documents of the deliverables pack (BRD, traceability matrix, test report) and exports any Markdown document to .docx and PDF. */
class DeliverablesBuilder
{
    private const STATUS = ['available' => '✅ Available', 'partial' => '🟡 Partial', 'missing' => '🔴 Missing'];

    private function cell(string $t): string
    {
        return trim(str_replace(['|', "\r", "\n"], ['\\|', ' ', ' '], $t));
    }

    /** One section per module with the behaviour delivered and an acceptance criterion for each requirement. */
    public function brd(array $data): string
    {
        $t = $data['totals'];
        $out = "# وثيقة متطلبات العمل (BRD) · Business Requirements Document\n\n";
        $out .= "> Generated by `php artisan tedc:deliverables` from `docs/rfp/gap-register.md` ({$data['generated_at']}). Edit the register, not this file.\n\n";
        $out .= "| Version | Date | Author | Status |\n|---|---|---|---|\n| 0.1 | ".substr((string) $data['generated_at'], 0, 10)." | Delivery team | Draft for the centre's review |\n\n";
        $out .= "**{$t['total']} requirements** · {$t['available']} available · {$t['partial']} partial · {$t['missing']} missing · {$t['mandatory']} mandatory (★).\n\n";
        $out .= "## الاعتماد · Approval\n\n| Role | Name | Signature | Date |\n|---|---|---|---|\n| Centre representative | | | |\n| Supplier representative | | | |\n\n";
        $n = 0;
        foreach ($data['modules'] as $m) {
            $n++;
            $out .= "## {$n}. {$m['title_en']} — {$m['title_ar']} ({$m['code']})\n\n| ID | Requirement | Status | Behaviour delivered | Acceptance criterion |\n|---|---|---|---|---|\n";
            foreach ($m['items'] as $i) {
                $criterion = match ($i['status']) {
                    'available' => 'Accepted when the behaviour described can be shown on the delivered system and the linked tests pass.',
                    'partial' => 'Accepted for the delivered part. The open part is listed in section "Open items" and needs a decision or an input from the centre.',
                    default => 'Not delivered. Listed in section "Open items".',
                };
                $out .= "| {$i['id']}".($i['mandatory'] ? ' ★' : '').' | '.$this->cell($i['requirement']).' | '.self::STATUS[$i['status']].' | '.$this->cell($i['evidence'])." | {$criterion} |\n";
            }
            $out .= "\n";
        }
        $out .= "## Open items — البنود المفتوحة\n\n";
        $open = collect($data['modules'])->flatMap(fn ($m) => collect($m['items'])->where('status', '!=', 'available'));
        if ($open->isEmpty()) {
            $out .= "None.\n";
        } else {
            $out .= "| ID | Status | Requirement | What is still needed |\n|---|---|---|---|\n";
            foreach ($open as $i) {
                $out .= "| {$i['id']} | ".self::STATUS[$i['status']].' | '.$this->cell($i['requirement']).' | '.$this->cell($i['evidence'])." |\n";
            }
        }

        return $out;
    }

    /** Requirement → implementation evidence → automated tests that exercise the same code. */
    public function traceability(array $data, ?string $testsDir = null): string
    {
        $tests = $this->testIndex($testsDir ?? base_path('tests'));
        $byPhase = (array) json_decode((string) @file_get_contents(base_path('../docs/rfp/phase-tests.json')), true);
        $phaseOf = $this->phaseOfIds((string) @file_get_contents(base_path('../docs/rfp/gap-register.md')));
        $out = "# مصفوفة التتبع · Traceability matrix\n\n> Generated by `php artisan tedc:deliverables`. The **Automated tests** column lists test files that mention the same classes or files as the evidence; it is a lead for the reviewer, not a proof of coverage. Tests of the phase that delivered the requirement (from `docs/rfp/phase-tests.json`, rebuilt by `scripts/rfp_phase_tests.py`) are listed too. A dash means no linked test: the requirement existed before the programme or is verified by UAT or documentation.\n\n";
        $out .= "| ID | Requirement | Status | Evidence (code and documents) | Automated tests |\n|---|---|---|---|---|\n";
        $linked = 0;
        $total = 0;
        foreach ($data['modules'] as $m) {
            foreach ($m['items'] as $i) {
                $total++;
                $paths = $this->evidencePaths($i['evidence']);
                $hits = array_values(array_unique(array_merge($this->matchTests($paths, $tests, $i['evidence']), isset($phaseOf[$i['id']]) ? ($byPhase[(string) $phaseOf[$i['id']]] ?? []) : [])));
                $linked += $hits ? 1 : 0;
                $out .= "| {$i['id']} | ".$this->cell($i['requirement']).' | '.self::STATUS[$i['status']].' | '.($paths ? $this->cell(implode(', ', array_map(fn ($p) => "`{$p}`", array_slice($paths, 0, 6)))) : $this->cell(mb_substr($i['evidence'], 0, 160))).' | '.($hits ? implode(', ', array_map(fn ($h) => "`{$h}`", array_slice($hits, 0, 4))) : '—')." |\n";
            }
        }

        return $out."\n**{$linked} of {$total}** requirements link to at least one automated test file.\n";
    }

    /** @return array<string, int> requirement id => the phase that closed it, from the register's «Open gaps by phase» lists */
    public function phaseOfIds(string $register): array
    {
        $map = [];
        $phase = null;
        foreach (preg_split('/\R/u', $register) ?: [] as $line) {
            if (preg_match('/^### Phase (\d+) — /u', $line, $m)) {
                $phase = (int) $m[1];
            } elseif (str_starts_with($line, '## ') && ! str_contains($line, 'by phase')) {
                $phase = null;
            } elseif ($phase !== null && preg_match('/^- \[[ x]\] \*\*([A-Z]+-\d+)\*\*/u', $line, $m)) {
                $map[$m[1]] = $phase;
            }
        }

        return $map;
    }

    /** @return list<string> backticked paths in an evidence text */
    public function evidencePaths(string $evidence): array
    {
        preg_match_all('/`([^`]+)`/u', $evidence, $m);

        return array_values(array_unique(array_filter($m[1], fn ($p) => preg_match('~[A-Za-z]/|\.(php|tsx?|dart|md|json|yml|bicep|sh)$~', $p) === 1)));
    }

    /** @return array<string, string> test file name => lowercase contents */
    private function testIndex(string $dir): array
    {
        $out = [];
        foreach (glob($dir.'/{Feature,Unit}/*.php', GLOB_BRACE) ?: [] as $f) {
            $out[basename($f)] = (string) file_get_contents($f);
        }

        return $out;
    }

    /** @param list<string> $paths @param array<string, string> $tests @return list<string> */
    private function matchTests(array $paths, array $tests, string $evidence = ''): array
    {
        $tokens = [];
        foreach ($paths as $p) {
            $base = pathinfo($p, PATHINFO_FILENAME);
            if (mb_strlen($base) >= 6 && ! str_ends_with($p, '.md')) {
                $tokens[] = $base;
            }
        }
        // Class names written without a path, and API routes (/admin/ekits) in the evidence text.
        preg_match_all('/\b[A-Z][a-z0-9]+(?:[A-Z][A-Za-z0-9]*)+\b/', $evidence, $m);
        foreach ($m[0] as $w) {
            if (mb_strlen($w) >= 7) {
                $tokens[] = $w;
            }
        }
        preg_match_all('~(?:GET|POST|PUT|PATCH|DELETE)\s+(/[a-z0-9/_{}-]+)~i', $evidence, $r);
        foreach ($r[1] as $route) {
            $tokens[] = preg_replace('~/\{[^}]+\}~', '', $route);
        }
        $tokens = array_values(array_unique(array_filter($tokens, fn ($t) => $t !== '' && $t !== '/')));
        $hits = [];
        foreach ($tests as $name => $body) {
            foreach ($tokens as $tok) {
                if (str_contains($body, $tok)) {
                    $hits[] = $name;
                    break;
                }
            }
        }

        return $hits;
    }

    /** The test inventory and, when a results file from `php artisan test` is given, the run's totals. */
    public function testReport(array $data, ?array $results, ?string $testsDir = null): string
    {
        $dir = $testsDir ?? base_path('tests');
        $files = [];
        $methods = 0;
        foreach (glob($dir.'/{Feature,Unit}/*.php', GLOB_BRACE) ?: [] as $f) {
            $src = (string) file_get_contents($f);
            $n = preg_match_all('/function test_|#\[Test\]/', $src);
            $files[basename($f)] = $n;
            $methods += $n;
        }
        ksort($files);
        $out = "# تقرير الاختبارات · Test report\n\n> Generated by `php artisan tedc:deliverables`.\n\n## 1. Automated suite\n\n";
        $out .= '- Test files: **'.count($files)."**; test methods: **{$methods}**.\n";
        if ($results) {
            $out .= "- Last recorded run: **{$results['passed']} of {$results['tests']} passed**, {$results['assertions']} assertions".(! empty($results['failed']) ? ", {$results['failed']} failed" : '').'.'."\n";
        } else {
            $out .= "- No run was attached. Run `php artisan test` and pass its JSON with `--results=` to record totals here; CI (`.github/workflows/ci.yml`) runs the suite on every push.\n";
        }
        $out .= "- Code style: `vendor/bin/pint --test`. Web: `npm run lint && npm run build`. Mobile: `flutter analyze && flutter test` in CI.\n\n";
        $out .= "## 2. Requirement status behind the tests\n\n{$data['totals']['available']} of {$data['totals']['total']} requirements are marked available; {$data['totals']['partial']} partial; {$data['totals']['missing']} missing (see the BRD, section \"Open items\").\n\n";
        $out .= "## 3. UAT\n\nUAT scripts per role follow `uat/template.md`. **UAT has not been executed with the centre**: the results table must be completed during the acceptance period.\n\n";
        $out .= "## 4. Performance and security\n\nSee `docs/security/` and `perf/`. The k6 scripts exist; **no load test has been run**, so no performance figure is claimed. Security scanning runs in `.github/workflows/security.yml`; an independent VAPT has not been performed.\n\n";
        $out .= "## 5. Test files\n\n| File | Tests |\n|---|---:|\n";
        foreach ($files as $name => $n) {
            $out .= "| {$name} | {$n} |\n";
        }

        return $out;
    }

    // ---- export ---------------------------------------------------------------------------------------

    public function docx(string $markdown): string
    {
        $w = new DocxWriter(null);
        $lines = preg_split('/\R/u', $markdown) ?: [];
        $bullets = [];
        $table = [];
        $flush = function () use (&$bullets, &$table, $w) {
            if ($bullets) {
                $w->bullets($bullets);
                $bullets = [];
            }
            if ($table) {
                $head = array_shift($table);
                $w->table($head, $table);
                $table = [];
            }
        };
        foreach ($lines as $line) {
            $line = rtrim($line);
            if (preg_match('/^\|(.+)\|$/u', $line, $m)) {
                $cells = array_map(fn ($c) => $this->inline(trim($c)), preg_split('/(?<!\\\\)\|/u', $m[1]) ?: []);
                if (! preg_match('/^[\s:|-]+$/', $m[1])) {
                    $table[] = array_map(fn ($c) => str_replace('\\|', '|', $c), $cells);
                }

                continue;
            }
            if ($table) {
                $flush();
            }
            if (preg_match('/^(#{1,6})\s+(.*)$/u', $line, $m)) {
                $flush();
                $w->heading($this->inline($m[2]), min(3, strlen($m[1])));
            } elseif (preg_match('/^\s*(?:[-*]|\d+\.)\s+(.*)$/u', $line, $m)) {
                $bullets[] = $this->inline($m[1]);
            } elseif (trim($line) === '') {
                $flush();
            } else {
                $flush();
                $w->text($this->inline(ltrim($line, "> \t")));
            }
        }
        $flush();

        return $w->bytes();
    }

    private function inline(string $t): string
    {
        return trim(preg_replace(['/\*\*(.+?)\*\*/u', '/`([^`]+)`/u', '/\[([^\]]+)\]\([^)]+\)/u', '/(?<![\w*])_(.+?)_(?![\w*])/u'], ['$1', '$1', '$1', '$1'], $t) ?? $t);
    }

    public function pdf(string $markdown, string $title): string
    {
        $env = new Environment([]);
        $env->addExtension(new CommonMarkCoreExtension);
        $env->addExtension(new GithubFlavoredMarkdownExtension);
        $html = (new MarkdownConverter($env))->convert($markdown)->getContent();
        // Bilingual text: every block that starts with Arabic is laid out right to left.
        $html = preg_replace_callback('~<(p|h[1-6]|li|td|th|blockquote)>(.*?)(?=</\1>)~su', function ($m) {
            $rtl = preg_match('/\p{Arabic}/u', mb_substr(strip_tags($m[2]), 0, 30)) === 1;

            return '<'.$m[1].($rtl ? ' dir="rtl" style="text-align:right"' : '').'>'.$m[2];
        }, $html) ?? $html;
        $theme = app(ThemeService::class);
        $center = $theme->centerName();
        $doc = '<html><head><meta charset="utf-8"><style>body{font-family:dejavusans;font-size:10pt;color:#1b2433}h1{font-size:20pt;color:#123b5d}h2{font-size:14pt;color:#123b5d;border-bottom:1pt solid #c9a24b}h3{font-size:11.5pt;color:#123b5d}table{border-collapse:collapse;width:100%;margin:6pt 0}td,th{border:.5pt solid #c8d0db;padding:3pt;font-size:8.5pt;vertical-align:top}th{background:#eef2f6}blockquote{border-left:3pt solid #c9a24b;margin:4pt 0;padding-left:6pt;color:#3a4658}code{font-size:8.5pt;background:#f3f5f8}</style></head><body>'.$html.'</body></html>';
        $mpdf = new Mpdf(['mode' => 'utf-8', 'format' => 'A4', 'margin_left' => 14, 'margin_right' => 14, 'margin_top' => 16, 'margin_bottom' => 16, 'default_font' => 'dejavusans', 'tempDir' => storage_path('app/mpdf'), 'autoScriptToLang' => true, 'autoLangToFont' => true]);
        $mpdf->SetTitle($title);
        $mpdf->SetFooter((is_array($center) ? ($center['en'] ?? '') : (string) $center).' · '.$title.' · {PAGENO}/{nbpg}');
        $mpdf->WriteHTML($doc);

        return $mpdf->Output('', 'S');
    }
}
