<?php

namespace App\Services;

/** Builds docs/rfp/compliance-sheet.md: the RFP's mandatory tables, pre-filled from the register, ready for the proposal. */
class RfpCompliance
{
    private const ANSWER = ['available' => 'Yes — نعم', 'partial' => 'Partial — جزئي', 'missing' => 'No — لا', 'vendor' => 'Vendor — للمورّد'];

    /** KPI table of the RFP: target, and the requirement id whose status answers it. */
    private const KPIS = [
        ['Average response time', '< 1.5 s', 'TEC-02'], ['Concurrent users', '10,000+', 'TEC-02'], ['Availability (uptime)', '99.9 %', 'NFR-01'],
        ['Error rate', '< 0.1 %', 'TEC-17'], ['Data integrity rate', '100 %', 'TEC-17'], ['Data completion rate', '100 %', 'TEC-17'],
        ['Course completion rate', '80–90 %', 'TEC-17'], ['Monthly active users', '70 % of the target population', 'TEC-17'],
        ['Learner satisfaction', '4.5 / 5', 'TEC-17'], ['Knowledge gain (pre/post)', '≥ 35 %', 'EVL-06'], ['Unauthorised access breaches', '0', 'NFR-15'],
    ];

    /** @param  array<string, mixed>  $data  the output of RfpRegister::parse() */
    public function markdown(array $data): string
    {
        $items = collect($data['modules'])->flatMap(fn ($m) => $m['items'])->keyBy('id');
        $t = $data['totals'];
        $out = "# RFP compliance sheet — صحيفة الامتثال\n\n";
        $out .= "> Generated by `php artisan tedc:rfp-status` from `docs/rfp/gap-register.md` — do not edit by hand; update the register instead. Fill the **Proposal page** column when the proposal is assembled.\n\n";
        $out .= "**{$t['total']} requirements** · {$t['available']} available · {$t['partial']} partial · {$t['missing']} missing · {$t['mandatory']} mandatory (★)\n\n";

        $out .= "## 1. The 31 main items — المتطلبات الرئيسية\n\n| # | Requirement | Yes/No | Evidence | Proposal page |\n|---:|---|---|---|---|\n";
        foreach ($data['mandatory31'] as $m) {
            $out .= "| {$m['no']} | {$this->cell($m['requirement'])} | ".self::ANSWER[$m['status']].' | '.$this->cell($m['notes'])." |  |\n";
        }

        foreach (['NFR' => '2. Infrastructure & Security — البنية التحتية والأمن', 'TEC' => '3. Technical requirements — المتطلبات التقنية'] as $code => $title) {
            $module = collect($data['modules'])->firstWhere('code', $code);
            $out .= "\n## {$title}\n\n| ID | Requirement | Yes/No | Evidence | Proposal page |\n|---|---|---|---|---|\n";
            foreach ($module['items'] ?? [] as $i) {
                $out .= "| {$i['id']}".($i['mandatory'] ? ' ★' : '')." | {$this->cell($i['requirement'])} | ".self::ANSWER[$i['status']].' | '.$this->cell($i['evidence'])." |  |\n";
            }
        }

        $out .= "\n## 4. KPIs — مؤشرات الأداء\n\n| KPI | Target | Yes/No | Evidence | Proposal page |\n|---|---|---|---|---|\n";
        foreach (self::KPIS as [$kpi, $target, $id]) {
            $i = $items->get($id);
            $out .= "| {$kpi} | {$target} | ".($i ? self::ANSWER[$i['status']] : '—').' | '.($i ? "{$id}: ".$this->cell($i['evidence']) : '')." |  |\n";
        }

        return $out;
    }

    private function cell(string $text): string
    {
        return trim(str_replace(['|', "\n"], ['/', ' '], $text));
    }
}
