<?php

namespace App\Services\Notifications;

/**
 * Every automatic notification of the platform ("action"), with its default wording. Administrators can switch
 * each one off and rewrite it (Settings → Notification templates); the placeholders are filled when it is sent.
 */
class NotificationCatalog
{
    /** Placeholders usable in a template. */
    public const VARIABLES = ['name', 'program', 'program_code', 'session', 'date', 'time', 'status', 'center', 'group', 'reason'];

    /** @return array<string, array{group: string, name_ar: string, name_en: string, title_ar: string, title_en: string, body_ar: string, body_en: string}> */
    public static function events(): array
    {
        $registration = fn (string $ar, string $en) => ['group' => 'registration', 'name_ar' => "تسجيل: {$ar}", 'name_en' => "Registration: {$en}",
            'title_ar' => 'تحديث حالة التسجيل', 'title_en' => 'Registration update',
            'body_ar' => 'تسجيلك في برنامج «{{program}}» {{status}}.', 'body_en' => 'Your registration for "{{program}}" is {{status}}.'];

        return [
            'trainer.assignment_proposed' => ['group' => 'program', 'name_ar' => 'اقتراح إسناد مدرب (يتطلب تعبئة نموذج)', 'name_en' => 'Trainer assignment proposed (form required)',
                'title_ar' => 'رُشّحت لتدريب مجموعة', 'title_en' => 'You were proposed for a group',
                'body_ar' => 'رُشّحت لمجموعة «{{group}}» من برنامج «{{program}}». عبّئ نموذج الإسناد لاستكمال الاعتماد.', 'body_en' => 'You were proposed for group "{{group}}" of "{{program}}". Fill in the assignment form to proceed.'],
            'trainer.assignment_decided' => ['group' => 'program', 'name_ar' => 'قرار إسناد مدرب', 'name_en' => 'Trainer assignment decision',
                'title_ar' => 'قرار بشأن إسنادك', 'title_en' => 'Decision on your assignment',
                'body_ar' => 'مجموعة «{{group}}» من برنامج «{{program}}»: {{status}}.', 'body_en' => 'Group "{{group}}" of "{{program}}": {{status}}.'],
            'kit.developer_assigned' => ['group' => 'program', 'name_ar' => 'إسناد تطوير حقيبة تدريبية', 'name_en' => 'Kit development assigned',
                'title_ar' => 'أُسند إليك تطوير حقيبة تدريبية', 'title_en' => 'You were assigned to develop a training kit',
                'body_ar' => 'مطلوب تطوير حقيبة برنامج «{{program}}» — الموعد النهائي {{date}}.', 'body_en' => 'Develop the kit of "{{program}}" — due {{date}}.'],
            'plan.submitted' => ['group' => 'program', 'name_ar' => 'خطة تدريبية بانتظار المراجعة', 'name_en' => 'A training plan awaits review',
                'title_ar' => 'خطة تدريبية بانتظار المراجعة', 'title_en' => 'A training plan awaits review',
                'body_ar' => '{{plan}}', 'body_en' => '{{plan}}'],
            'plan.returned' => ['group' => 'program', 'name_ar' => 'أُعيدت الخطة التدريبية للتعديل', 'name_en' => 'The training plan was returned for changes',
                'title_ar' => 'أُعيدت الخطة التدريبية للتعديل', 'title_en' => 'The training plan was returned for changes',
                'body_ar' => '{{plan}}', 'body_en' => '{{plan}}'],
            'plan.approved' => ['group' => 'program', 'name_ar' => 'اعتُمدت الخطة التدريبية', 'name_en' => 'The training plan was approved',
                'title_ar' => 'اعتُمدت الخطة التدريبية', 'title_en' => 'The training plan was approved',
                'body_ar' => '{{plan}}', 'body_en' => '{{plan}}'],
            'plan.deviation_detected' => ['group' => 'program', 'name_ar' => 'انحراف في الخطة التدريبية', 'name_en' => 'Deviation in the training plan',
                'title_ar' => 'انحراف في الخطة التدريبية', 'title_en' => 'Deviation in the training plan',
                'body_ar' => '{{plan}}', 'body_en' => '{{plan}}'],
            'internal_workshop.submitted' => ['group' => 'program', 'name_ar' => 'ورشة داخلية بانتظار الاعتماد', 'name_en' => 'Internal workshop awaiting approval',
                'title_ar' => 'ورشة داخلية بانتظار الاعتماد', 'title_en' => 'An internal workshop awaits approval',
                'body_ar' => 'ورشة «{{program}}» بانتظار قرار المركز.', 'body_en' => 'Workshop "{{program}}" awaits the centre\'s decision.'],
            'internal_workshop.decided' => ['group' => 'program', 'name_ar' => 'قرار بشأن ورشة داخلية', 'name_en' => 'Internal workshop decision',
                'title_ar' => 'قرار بشأن ورشتك الداخلية', 'title_en' => 'Decision on your internal workshop',
                'body_ar' => 'صدر قرار المركز بشأن ورشة «{{program}}».', 'body_en' => 'The centre has decided on workshop "{{program}}".'],
            'needs.cycle_opened' => ['group' => 'program', 'name_ar' => 'فتح دورة الاحتياجات', 'name_en' => 'Needs cycle opened',
                'title_ar' => 'فُتحت دورة الاحتياجات التدريبية', 'title_en' => 'The training needs cycle is open',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'needs.cycle_closing' => ['group' => 'program', 'name_ar' => 'قرب إغلاق دورة الاحتياجات', 'name_en' => 'Needs cycle closing soon',
                'title_ar' => 'تغلق دورة الاحتياجات قريباً', 'title_en' => 'The needs cycle closes soon',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'proposal.reviewed' => ['group' => 'program', 'name_ar' => 'مراجعة مقترح برنامج', 'name_en' => 'Program proposal reviewed',
                'title_ar' => 'تمت مراجعة مقترحك', 'title_en' => 'Your proposal was reviewed',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'request.reviewed' => ['group' => 'program', 'name_ar' => 'مراجعة طلب مؤسسي', 'name_en' => 'Institutional request reviewed',
                'title_ar' => 'تمت مراجعة طلبك', 'title_en' => 'Your request was reviewed',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'individual_need.awaiting_manager' => ['group' => 'program', 'name_ar' => 'احتياج فردي بانتظار المدير', 'name_en' => 'Individual need awaiting the manager',
                'title_ar' => 'احتياجات تدريبية بانتظار اعتمادك', 'title_en' => 'Training needs await your approval',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'individual_need.decided' => ['group' => 'program', 'name_ar' => 'قرار بشأن احتياج فردي', 'name_en' => 'Individual need decision',
                'title_ar' => 'قرار بشأن احتياجك التدريبي', 'title_en' => 'Decision on your training need',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'instrument.awaiting_approval' => ['group' => 'program', 'name_ar' => 'أداة بانتظار الاعتماد', 'name_en' => 'Instrument awaiting approval',
                'title_ar' => 'أداة بانتظار اعتمادك', 'title_en' => 'An instrument awaits your approval',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'instrument.decided' => ['group' => 'program', 'name_ar' => 'قرار بشأن أداة', 'name_en' => 'Instrument decision',
                'title_ar' => 'قرار بشأن الأداة', 'title_en' => 'Decision on your instrument',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'needs.rules_generated' => ['group' => 'program', 'name_ar' => 'احتياجات مولّدة بالقواعد', 'name_en' => 'Rule-generated needs',
                'title_ar' => 'احتياجات جديدة مولّدة آلياً', 'title_en' => 'New needs were generated automatically',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'withdrawal.requested' => ['group' => 'registration', 'name_ar' => 'طلب انسحاب بانتظار القرار', 'name_en' => 'Withdrawal request awaiting decision',
                'title_ar' => 'طلب انسحاب بانتظار قرارك', 'title_en' => 'A withdrawal request awaits your decision',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'withdrawal.decided' => ['group' => 'registration', 'name_ar' => 'قرار بشأن الانسحاب', 'name_en' => 'Withdrawal decision',
                'title_ar' => 'قرار بشأن طلب الانسحاب', 'title_en' => 'Decision on your withdrawal request',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'registration.pending_manager' => ['group' => 'registration', 'name_ar' => 'تسجيل بانتظار المدير', 'name_en' => 'Registration awaiting the manager',
                'title_ar' => 'طلب تسجيل بانتظار موافقتك', 'title_en' => 'A registration awaits your approval',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'registration.withdrawn' => ['group' => 'registration', 'name_ar' => 'انسحاب من برنامج', 'name_en' => 'Withdrawn from a program',
                'title_ar' => 'تم انسحابك من البرنامج', 'title_en' => 'You withdrew from the program',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'external_request.submitted' => ['group' => 'registration', 'name_ar' => 'طلب تسجيل خارجي جديد', 'name_en' => 'New external registration request',
                'title_ar' => 'طلب تسجيل خارجي جديد', 'title_en' => 'New external registration request',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'attendance.absence_warning' => ['group' => 'attendance', 'name_ar' => 'تنبيه غياب', 'name_en' => 'Absence warning',
                'title_ar' => 'تنبيه غياب', 'title_en' => 'Absence warning',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'attendance.absence_breach' => ['group' => 'attendance', 'name_ar' => 'تجاوز حد الغياب', 'name_en' => 'Absence limit exceeded',
                'title_ar' => 'تجاوز الغياب الحد المسموح', 'title_en' => 'Absence limit exceeded',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'excuse.submitted' => ['group' => 'attendance', 'name_ar' => 'عذر غياب جديد', 'name_en' => 'New absence excuse',
                'title_ar' => 'عذر غياب بانتظار قرارك', 'title_en' => 'An absence excuse awaits your decision',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'excuse.decided' => ['group' => 'attendance', 'name_ar' => 'قرار بشأن عذر', 'name_en' => 'Excuse decision',
                'title_ar' => 'قرار بشأن عذر الغياب', 'title_en' => 'Decision on your absence excuse',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'leave.recorded' => ['group' => 'attendance', 'name_ar' => 'تسجيل استئذان', 'name_en' => 'Leave recorded',
                'title_ar' => 'سُجّل استئذان', 'title_en' => 'A leave was recorded',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'room.booking_conflict' => ['group' => 'attendance', 'name_ar' => 'تعارض حجز قاعة', 'name_en' => 'Room booking conflict',
                'title_ar' => 'تعارض في حجز القاعة', 'title_en' => 'A room booking conflicts',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'logistics.request_new' => ['group' => 'attendance', 'name_ar' => 'طلب لوجستي جديد', 'name_en' => 'New logistics request',
                'title_ar' => 'طلب لوجستي جديد', 'title_en' => 'New logistics request',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'logistics.request_updated' => ['group' => 'attendance', 'name_ar' => 'تحديث طلب لوجستي', 'name_en' => 'Logistics request update',
                'title_ar' => 'تحديث على طلبك اللوجستي', 'title_en' => 'Update on your logistics request',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'logistics.request_overdue' => ['group' => 'attendance', 'name_ar' => 'طلب لوجستي متأخر', 'name_en' => 'Logistics request overdue',
                'title_ar' => 'طلب لوجستي متأخر', 'title_en' => 'A logistics request is overdue',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'device.sync_failed' => ['group' => 'attendance', 'name_ar' => 'فشل مزامنة جهاز', 'name_en' => 'Device sync failed',
                'title_ar' => 'فشلت مزامنة جهاز البصمة', 'title_en' => 'A fingerprint device failed to sync',
                'body_ar' => '{{detail}}', 'body_en' => '{{detail}}'],
            'group.status_changed' => ['group' => 'program', 'name_ar' => 'تغيير حالة مجموعة تدريبية', 'name_en' => 'Training group status changed',
                'title_ar' => 'تغيّرت حالة مجموعة تدريبية', 'title_en' => 'A training group changed status',
                'body_ar' => 'مجموعة «{{group}}» من برنامج «{{program}}»: {{status}}.', 'body_en' => 'Group "{{group}}" of "{{program}}": {{status}}.'],
            'group.postponed' => ['group' => 'program', 'name_ar' => 'تأجيل مجموعة تدريبية', 'name_en' => 'Training group postponed',
                'title_ar' => 'تم تأجيل مجموعة تدريبية', 'title_en' => 'A training group was postponed',
                'body_ar' => 'تأجّلت مجموعة «{{group}}» من برنامج «{{program}}». السبب: {{reason}}.', 'body_en' => 'Group "{{group}}" of "{{program}}" was postponed. Reason: {{reason}}.'],
            'group.cancelled' => ['group' => 'program', 'name_ar' => 'إلغاء مجموعة تدريبية', 'name_en' => 'Training group cancelled',
                'title_ar' => 'تم إلغاء مجموعة تدريبية', 'title_en' => 'A training group was cancelled',
                'body_ar' => 'أُلغيت مجموعة «{{group}}» من برنامج «{{program}}». السبب: {{reason}}.', 'body_en' => 'Group "{{group}}" of "{{program}}" was cancelled. Reason: {{reason}}.'],
            'program.assigned' => ['group' => 'registration', 'name_ar' => 'إسناد برنامج إلى متدرب', 'name_en' => 'Program assigned to a trainee',
                'title_ar' => 'تم إسنادك إلى برنامج تدريبي', 'title_en' => 'You have been assigned to a program',
                'body_ar' => 'تم تسجيلك في برنامج «{{program}}» — يبدأ {{date}}. راجع تفاصيله في تطبيقك.', 'body_en' => 'You have been enrolled in "{{program}}" — it starts {{date}}. See the details in your app.'],
            'trainer.assigned' => ['group' => 'program', 'name_ar' => 'إسناد مدرب إلى برنامج', 'name_en' => 'Trainer assigned to a program',
                'title_ar' => 'أُسند إليك برنامج تدريبي', 'title_en' => 'A program was assigned to you',
                'body_ar' => 'أنت مدرب برنامج «{{program}}» — يبدأ {{date}}. راجع جلساتك وقاعتك في تطبيقك.', 'body_en' => 'You are the trainer of "{{program}}" — it starts {{date}}. See your sessions and room in the app.'],
            'registration.new_pending' => ['group' => 'registration', 'name_ar' => 'تسجيل جديد بانتظار الاعتماد (للإدارة)', 'name_en' => 'New registration awaiting approval (staff)',
                'title_ar' => 'تسجيل جديد بانتظار اعتمادك', 'title_en' => 'A new registration awaits your approval',
                'body_ar' => 'سجّل {{name}} في برنامج «{{program}}». راجع الطلب واعتمده أو ارفضه.', 'body_en' => '{{name}} registered for "{{program}}". Review and approve or reject.'],
            'registration.approved' => $registration('اعتماد', 'approved'),
            'registration.rejected' => $registration('رفض', 'rejected'),
            'registration.pending' => $registration('قيد المراجعة', 'under review'),
            'registration.waitlisted' => $registration('قائمة الانتظار', 'waiting list'),
            'registration.cancelled' => $registration('إلغاء', 'cancelled'),
            'registration.completed' => $registration('إكمال', 'completed'),
            'program.invite' => ['group' => 'program', 'name_ar' => 'دعوة إلى برنامج جديد', 'name_en' => 'Invitation to a new program',
                'title_ar' => 'برنامج تدريبي جديد يناسبك', 'title_en' => 'A new training program for you',
                'body_ar' => '«{{program}}» متاح للتسجيل ضمن الفئة المستهدفة.', 'body_en' => '"{{program}}" is open to your group.'],
            'survey.open' => ['group' => 'survey', 'name_ar' => 'استبيان البرنامج متاح', 'name_en' => 'Program survey is open',
                'title_ar' => 'استبيان البرنامج متاح الآن', 'title_en' => 'The program survey is open',
                'body_ar' => 'يمكنك الآن تعبئة استبيان تقييم برنامج «{{program}}». رأيك يهمّنا.', 'body_en' => 'You can now fill in the evaluation survey of "{{program}}". Your opinion matters.'],
            'session.reminder' => ['group' => 'session', 'name_ar' => 'تذكير بجلسة', 'name_en' => 'Session reminder',
                'title_ar' => 'تذكير بجلسة تدريبية', 'title_en' => 'Training session reminder',
                'body_ar' => 'جلسة «{{session}}» من برنامج «{{program}}» تبدأ {{date}} {{time}}.', 'body_en' => '"{{session}}" ({{program}}) starts {{date}} {{time}}.'],
            'session.attendance_open' => ['group' => 'session', 'name_ar' => 'بدء تسجيل الحضور', 'name_en' => 'Check-in is open',
                'title_ar' => 'بدأ تسجيل الحضور', 'title_en' => 'Check-in is open',
                'body_ar' => 'افتح التطبيق وامسح رمز الحضور لجلسة «{{session}}». يتطلب التسجيل وجودك في مكان التدريب.', 'body_en' => 'Open the app and scan the code for "{{session}}". You must be at the venue to check in.'],
            'session.attendance_missed' => ['group' => 'session', 'name_ar' => 'لم تسجّل حضورك', 'name_en' => 'Check-in missed',
                'title_ar' => 'لم تسجّل حضورك بعد', 'title_en' => 'You have not checked in yet',
                'body_ar' => 'بدأت جلسة «{{session}}». سجّل حضورك الآن قبل أن يُحتسب تأخير أكبر.', 'body_en' => '"{{session}}" has started. Check in now to avoid being marked late.'],
            'task.approved' => ['group' => 'task', 'name_ar' => 'المهام: اعتماد', 'name_en' => 'Task: approved', 'title_ar' => 'تم اعتماد مهمتك', 'title_en' => 'Your task was approved', 'body_ar' => '{{program}}', 'body_en' => '{{program}}'],
            'task.needs_changes' => ['group' => 'task', 'name_ar' => 'المهام: مطلوب تعديل', 'name_en' => 'Task: changes requested', 'title_ar' => 'مطلوب تعديل على مهمتك', 'title_en' => 'Changes requested on your task', 'body_ar' => '{{program}}', 'body_en' => '{{program}}'],
            'course.completed' => ['group' => 'course', 'name_ar' => 'إتمام المحتوى التدريبي', 'name_en' => 'Course completed',
                'title_ar' => 'أتممت المحتوى التدريبي 🎉', 'title_en' => 'You completed the course 🎉',
                'body_ar' => 'أنهيت كل دروس برنامج «{{program}}».', 'body_en' => 'You finished every lesson of "{{program}}".'],
            'course.nudge' => ['group' => 'course', 'name_ar' => 'تذكير بمتابعة المحتوى', 'name_en' => 'Course reminder',
                'title_ar' => 'أكمل من حيث توقفت', 'title_en' => 'Pick up where you left off',
                'body_ar' => 'محتوى برنامج «{{program}}» ينتظرك — تبقّى لك القليل.', 'body_en' => 'The content of "{{program}}" is waiting for you — you are close.'],
            'certificate.issued' => ['group' => 'certificate', 'name_ar' => 'إصدار الشهادة', 'name_en' => 'Certificate issued',
                'title_ar' => 'تم إصدار شهادتك', 'title_en' => 'Your certificate is ready',
                'body_ar' => 'تهانينا! صدرت شهادة إتمام برنامج «{{program}}».', 'body_en' => 'Congratulations! Your certificate for "{{program}}" has been issued.'],
            'certificate.available' => ['group' => 'certificate', 'name_ar' => 'الشهادة جاهزة للتحميل (متدرب)', 'name_en' => 'Certificate ready to download (trainee)',
                'title_ar' => 'شهادتك جاهزة للتحميل', 'title_en' => 'Your certificate is ready to download',
                'body_ar' => 'شكرًا لتعبئة الاستبيان. يمكنك الآن تحميل شهادة برنامج «{{program}}» من تطبيقك.', 'body_en' => 'Thank you for the survey. You can now download your certificate for "{{program}}" in the app.'],
            'certificate.survey_needed' => ['group' => 'certificate', 'name_ar' => 'الشهادة بانتظار الاستبيان', 'name_en' => 'Certificate waiting for the survey',
                'title_ar' => 'شهادتك بانتظار تعبئة الاستبيان', 'title_en' => 'Your certificate is waiting for the survey',
                'body_ar' => 'صدرت شهادة برنامج «{{program}}». عبّئ استبيان البرنامج لتتمكن من تحميلها.', 'body_en' => 'Your certificate for "{{program}}" is issued. Fill in the program survey to download it.'],
            'certificate.trainer_available' => ['group' => 'certificate', 'name_ar' => 'شهادة شكر المدرب جاهزة', 'name_en' => 'Trainer thank-you certificate ready',
                'title_ar' => 'شهادة الشكر والتقدير جاهزة', 'title_en' => 'Your thank-you certificate is ready',
                'body_ar' => 'أكملتَ ساعات برنامج «{{program}}». يمكنك الآن تحميل شهادة الشكر والتقدير من تطبيقك.', 'body_en' => 'You completed your hours in "{{program}}". You can now download your thank-you certificate in the app.'],
            'certificate.sent' => ['group' => 'certificate', 'name_ar' => 'إرسال الشهادة بالبريد', 'name_en' => 'Certificate e-mailed',
                'title_ar' => 'وصلتك شهادتك', 'title_en' => 'Your certificate was sent',
                'body_ar' => 'أُرسلت شهادة «{{program}}» إلى بريدك الإلكتروني.', 'body_en' => 'The certificate for "{{program}}" was sent to your e-mail.'],
            'impact.survey' => ['group' => 'survey', 'name_ar' => 'استبيان قياس الأثر', 'name_en' => 'Impact survey',
                'title_ar' => 'استبيان أثر التدريب', 'title_en' => 'Training impact survey',
                'body_ar' => 'شاركنا كيف طبّقت ما تعلمته في برنامج «{{program}}».', 'body_en' => 'Tell us how you applied what you learned in "{{program}}".'],
            'profile.request_approved' => ['group' => 'account', 'name_ar' => 'الموافقة على طلب تعديل بيانات', 'name_en' => 'Data change request approved',
                'title_ar' => 'تمت الموافقة على طلب تعديل بياناتك', 'title_en' => 'Your change request was approved', 'body_ar' => 'راجع بياناتك في «حسابي».', 'body_en' => 'Check your details in "My account".'],
            'profile.request_rejected' => ['group' => 'account', 'name_ar' => 'رفض طلب تعديل بيانات', 'name_en' => 'Data change request rejected',
                'title_ar' => 'لم تتم الموافقة على طلب التعديل', 'title_en' => 'Your change request was not approved', 'body_ar' => 'راجع التفاصيل في «حسابي».', 'body_en' => 'See the details in "My account".'],
            'needs_survey.invite' => ['group' => 'survey', 'name_ar' => 'دعوة إلى استبانة الاحتياجات', 'name_en' => 'Needs survey invitation',
                'title_ar' => 'استبانة جديدة', 'title_en' => 'New survey', 'body_ar' => 'شاركنا احتياجاتك التدريبية — تستغرق دقائق قليلة.', 'body_en' => 'Share your training needs — it only takes a few minutes.'],
            'needs_survey.reminder' => ['group' => 'survey', 'name_ar' => 'تذكير باستبانة الاحتياجات', 'name_en' => 'Needs survey reminder',
                'title_ar' => 'تذكير باستبانة', 'title_en' => 'Survey reminder', 'body_ar' => 'لم نستلم إجاباتك بعد، رأيك يصنع برامج التدريب القادمة.', 'body_en' => 'We have not received your answers yet — your input shapes the next programs.'],
        ];
    }

    public static function groups(): array
    {
        return ['registration' => ['ar' => 'التسجيل والإسناد', 'en' => 'Registration & assignment'], 'program' => ['ar' => 'البرامج', 'en' => 'Programs'], 'survey' => ['ar' => 'الاستبيانات', 'en' => 'Surveys'],
            'session' => ['ar' => 'الجلسات والحضور', 'en' => 'Sessions & attendance'], 'task' => ['ar' => 'المهام', 'en' => 'Tasks'], 'certificate' => ['ar' => 'الشهادات', 'en' => 'Certificates'], 'course' => ['ar' => 'المحتوى التدريبي', 'en' => 'Online course'], 'account' => ['ar' => 'الحساب', 'en' => 'Account'], 'custom' => ['ar' => 'قوالب مخصصة', 'en' => 'Custom templates']];
    }
}
